### PR TITLE
Front-end changes for Katsu case-insensitive search

### PR DESCRIPTION
**Pull request by gsfk**
update search equality operator to allow for Katsu case-insensitive search. Needs testing.

### CODE REVIEW

**Review by zxenia — APPROVED** [review]
LGTM!

**Comment by davidlougheed** [comment]
This is incorrect since ico is contains not equals

**Comment by davidlougheed** [comment]
Instead, add new operators and change which one is the default if you want to make it easier to search

**Comment by davidlougheed** [comment]
To go a bit more into detail, you should never be changing those constants except if an operator is renamed in bento_lib; they are just supposed to be JS representations of the operator strings themselves (eq = OPERATOR_EQUALS, etc)

I suggest taking a closer look at the search schemas coming from the different data services and seeing how the front end uses some of these fields to build the search interface.

**Comment by zxenia** [comment]
@davidlougheed just to clarify a little bit here, are those changes mainly should be done on the front-end (bento_web) or should I change those operators in katsu or in bento_lib?

**Comment by gsfk** [comment]
Draft of a more appropriate fix. Needs a few more changes if text-insensitive search is meant as default. Needs testing.

**Comment by brouillette** [comment]
LGTM!

**Pull request merged**
