### PR TITLE
feat: drop box pdf viewer + file load error handling

### PR DESCRIPTION
**Pull request by davidlougheed**

### CODE REVIEW

**Review by gsfk — COMMENTED** [review]
Looks good with just two issues: 

- breaks on file names with spaces (and presumably any other non-url character)
- when _does_ break, the spinner runs forever 

I don't see a problem with forbidding spaces in filenames, but the failure mode could be nicer

**Comment by davidlougheed** [comment]
good catch, will figure something out!

**Comment by davidlougheed** [comment]
this led me down a rabbit hole-- this is caused by a bug in gateway configs and a bug in drop box, but the web part is actually not at fault

**Comment by davidlougheed** [comment]
https://github.com/bento-platform/bentoV2/pull/118 PR 1 related to this

**Comment by davidlougheed** [comment]
https://github.com/bento-platform/bento_drop_box_service/pull/24 PR 2

**Pull request merged**
